//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _02.CLIWEB.ConversionServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConversionServiceReference.IConversionService")]
    public interface IConversionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/KilometrosAMillas", ReplyAction="http://tempuri.org/IConversionService/KilometrosAMillasResponse")]
        double KilometrosAMillas(double km);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/KilometrosAMillas", ReplyAction="http://tempuri.org/IConversionService/KilometrosAMillasResponse")]
        System.Threading.Tasks.Task<double> KilometrosAMillasAsync(double km);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/MetrosAPies", ReplyAction="http://tempuri.org/IConversionService/MetrosAPiesResponse")]
        double MetrosAPies(double m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/MetrosAPies", ReplyAction="http://tempuri.org/IConversionService/MetrosAPiesResponse")]
        System.Threading.Tasks.Task<double> MetrosAPiesAsync(double m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/PulgadasACentimetros", ReplyAction="http://tempuri.org/IConversionService/PulgadasACentimetrosResponse")]
        double PulgadasACentimetros(double p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/PulgadasACentimetros", ReplyAction="http://tempuri.org/IConversionService/PulgadasACentimetrosResponse")]
        System.Threading.Tasks.Task<double> PulgadasACentimetrosAsync(double p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/KilogramosALibras", ReplyAction="http://tempuri.org/IConversionService/KilogramosALibrasResponse")]
        double KilogramosALibras(double kg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/KilogramosALibras", ReplyAction="http://tempuri.org/IConversionService/KilogramosALibrasResponse")]
        System.Threading.Tasks.Task<double> KilogramosALibrasAsync(double kg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/GramosAOnzas", ReplyAction="http://tempuri.org/IConversionService/GramosAOnzasResponse")]
        double GramosAOnzas(double g);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/GramosAOnzas", ReplyAction="http://tempuri.org/IConversionService/GramosAOnzasResponse")]
        System.Threading.Tasks.Task<double> GramosAOnzasAsync(double g);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/LibrasAKilogramos", ReplyAction="http://tempuri.org/IConversionService/LibrasAKilogramosResponse")]
        double LibrasAKilogramos(double lb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/LibrasAKilogramos", ReplyAction="http://tempuri.org/IConversionService/LibrasAKilogramosResponse")]
        System.Threading.Tasks.Task<double> LibrasAKilogramosAsync(double lb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/CelsiusAFahrenheit", ReplyAction="http://tempuri.org/IConversionService/CelsiusAFahrenheitResponse")]
        double CelsiusAFahrenheit(double c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/CelsiusAFahrenheit", ReplyAction="http://tempuri.org/IConversionService/CelsiusAFahrenheitResponse")]
        System.Threading.Tasks.Task<double> CelsiusAFahrenheitAsync(double c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/FahrenheitACelsius", ReplyAction="http://tempuri.org/IConversionService/FahrenheitACelsiusResponse")]
        double FahrenheitACelsius(double f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/FahrenheitACelsius", ReplyAction="http://tempuri.org/IConversionService/FahrenheitACelsiusResponse")]
        System.Threading.Tasks.Task<double> FahrenheitACelsiusAsync(double f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/CelsiusAKelvin", ReplyAction="http://tempuri.org/IConversionService/CelsiusAKelvinResponse")]
        double CelsiusAKelvin(double c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/CelsiusAKelvin", ReplyAction="http://tempuri.org/IConversionService/CelsiusAKelvinResponse")]
        System.Threading.Tasks.Task<double> CelsiusAKelvinAsync(double c);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConversionServiceChannel : _02.CLIWEB.ConversionServiceReference.IConversionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConversionServiceClient : System.ServiceModel.ClientBase<_02.CLIWEB.ConversionServiceReference.IConversionService>, _02.CLIWEB.ConversionServiceReference.IConversionService {
        
        public ConversionServiceClient() {
        }
        
        public ConversionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConversionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConversionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConversionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double KilometrosAMillas(double km) {
            return base.Channel.KilometrosAMillas(km);
        }
        
        public System.Threading.Tasks.Task<double> KilometrosAMillasAsync(double km) {
            return base.Channel.KilometrosAMillasAsync(km);
        }
        
        public double MetrosAPies(double m) {
            return base.Channel.MetrosAPies(m);
        }
        
        public System.Threading.Tasks.Task<double> MetrosAPiesAsync(double m) {
            return base.Channel.MetrosAPiesAsync(m);
        }
        
        public double PulgadasACentimetros(double p) {
            return base.Channel.PulgadasACentimetros(p);
        }
        
        public System.Threading.Tasks.Task<double> PulgadasACentimetrosAsync(double p) {
            return base.Channel.PulgadasACentimetrosAsync(p);
        }
        
        public double KilogramosALibras(double kg) {
            return base.Channel.KilogramosALibras(kg);
        }
        
        public System.Threading.Tasks.Task<double> KilogramosALibrasAsync(double kg) {
            return base.Channel.KilogramosALibrasAsync(kg);
        }
        
        public double GramosAOnzas(double g) {
            return base.Channel.GramosAOnzas(g);
        }
        
        public System.Threading.Tasks.Task<double> GramosAOnzasAsync(double g) {
            return base.Channel.GramosAOnzasAsync(g);
        }
        
        public double LibrasAKilogramos(double lb) {
            return base.Channel.LibrasAKilogramos(lb);
        }
        
        public System.Threading.Tasks.Task<double> LibrasAKilogramosAsync(double lb) {
            return base.Channel.LibrasAKilogramosAsync(lb);
        }
        
        public double CelsiusAFahrenheit(double c) {
            return base.Channel.CelsiusAFahrenheit(c);
        }
        
        public System.Threading.Tasks.Task<double> CelsiusAFahrenheitAsync(double c) {
            return base.Channel.CelsiusAFahrenheitAsync(c);
        }
        
        public double FahrenheitACelsius(double f) {
            return base.Channel.FahrenheitACelsius(f);
        }
        
        public System.Threading.Tasks.Task<double> FahrenheitACelsiusAsync(double f) {
            return base.Channel.FahrenheitACelsiusAsync(f);
        }
        
        public double CelsiusAKelvin(double c) {
            return base.Channel.CelsiusAKelvin(c);
        }
        
        public System.Threading.Tasks.Task<double> CelsiusAKelvinAsync(double c) {
            return base.Channel.CelsiusAKelvinAsync(c);
        }
    }
}
